In [1]:
#Libraries needed for data quality
import pandas as pd 
import numpy as np

In [2]:
darwin = pd.read_csv('DARWIN.csv')
darwin.head()

,ID,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,id_1,5160,0.000013,120.804174,86.853334,957,6601,0.361800,0.217459,103.828754,...,0.141434,0.024471,5.596487,3.184589,71,40120,1749.278166,296102.7676,144605,P
1,id_2,51980,0.000016,115.318238,83.448681,1694,6998,0.272513,0.144880,99.383459,...,0.049663,0.018368,1.665973,0.950249,129,126700,1504.768272,278744.2850,298640,P
2,id_3,2600,0.000010,229.933997,172.761858,2333,5802,0.387020,0.181342,201.347928,...,0.178194,0.017174,4.000781,2.392521,74,45480,1431.443492,144411.7055,79025,P
3,id_4,2130,0.000010,369.403342,183.193104,1756,8159,0.556879,0.164502,276.298223,...,0.113905,0.019860,4.206746,1.613522,123,67945,1465.843329,230184.7154,181220,P
4,id_5,2310,0.000007,257.997131,111.275889,987,4732,0.266077,0.145104,184.636510,...,0.121782,0.020872,3.319036,1.680629,92,37285,1841.702561,158290.0255,72575,P

In [3]:
darwin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Columns: 452 entries, ID to class
dtypes: float64(300), int64(150), object(2)
memory usage: 614.6+ KB

In [4]:
darwin.describe()

,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,mean_jerk_in_air1,...,mean_gmrt25,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25
count,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,...,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,1.740000e+02
mean,5664.166667,0.000010,297.666685,200.504413,1977.965517,7323.896552,0.416374,0.179823,249.085549,0.067556,...,221.360646,0.148286,0.019934,4.472643,2.871613,85.839080,43109.712644,1629.585962,163061.767360,1.642033e+05
std,12653.772746,0.000003,183.943181,111.629546,1648.306365,2188.290512,0.381837,0.064693,132.698462,0.074776,...,63.762013,0.062207,0.002388,1.501411,0.852809,27.485518,19092.024337,324.142316,56845.610814,4.969397e+05
min,65.000000,0.000002,28.734515,29.935835,754.000000,561.000000,0.067748,0.096631,41.199445,0.011861,...,69.928033,0.030169,0.014987,1.323565,0.950249,32.000000,15930.000000,474.049462,26984.926660,2.998000e+04
25%,1697.500000,0.000008,174.153023,136.524742,1362.500000,6124.000000,0.218209,0.146647,161.136182,0.029523,...,178.798382,0.107732,0.018301,3.485934,2.401199,66.000000,32803.750000,1499.112088,120099.046800,5.917500e+04
50%,2890.000000,0.000009,255.791452,176.494494,1681.000000,6975.500000,0.275184,0.163659,224.445268,0.039233,...,217.431621,0.140483,0.019488,4.510578,2.830672,81.000000,37312.500000,1729.385010,158236.771800,7.611500e+04
75%,4931.250000,0.000011,358.917885,234.052560,2082.750000,8298.500000,0.442706,0.188879,294.392298,0.071057,...,264.310776,0.199168,0.021134,5.212794,3.335828,101.500000,46533.750000,1865.626974,200921.078475,1.275425e+05
max,109965.000000,0.000028,1168.328276,865.210522,18602.000000,15783.000000,2.772566,0.627350,836.784702,0.543199,...,437.373267,0.375078,0.029227,10.416715,5.602909,209.000000,139575.000000,1999.775983,352981.850000,5.704200e+06

### Subset of tasks 

Inspect 5 of the 25 tasks to see how effective they were at classifying participants as healthy or with Alzheimer's.

- **Task 3:** join two points with a vertical line, continuously for four times (g)
- **Task 8:**  write cursively a sequence of four lowercase letter I in a single smooth movement (c)
- **Task 13:** copy the word “mamma” above a line (c)
- **Task 23:** write a telephone number under dictation. (m)

In [23]:
# ID column 
# Identifies each participant
id_col = darwin['ID']
id_col[0:5]

0    id_1
1    id_2
2    id_3
3    id_4
4    id_5
Name: ID, dtype: object

In [24]:
# Class column 
# P = patient (has Alzheimer's)
# H = healthy
class_col = darwin['class']
class_col[0:5]

0    P
1    P
2    P
3    P
4    P
Name: class, dtype: object

In [25]:
# Task 3, 13, 23
three = [col for col in darwin if col.endswith('3')]
three[0:5]

['air_time3',
 'disp_index3',
 'gmrt_in_air3',
 'gmrt_on_paper3',
 'max_x_extension3']

In [27]:
# Task 8 & 18
eight = [col for col in darwin if col.endswith('8')]
eight[0:5]

['air_time8',
 'disp_index8',
 'gmrt_in_air8',
 'gmrt_on_paper8',
 'max_x_extension8']

In [30]:
# Combine the 5 tasks
tasks = three + eight

# First 5 columns reference task 3
tasks[:5]

['air_time3',
 'disp_index3',
 'gmrt_in_air3',
 'gmrt_on_paper3',
 'max_x_extension3']

In [32]:
# last 5 columns reference task 18
tasks[85:]

['num_of_pendown18',
 'paper_time18',
 'pressure_mean18',
 'pressure_var18',
 'total_time18']

In [33]:
# Subset entire dataframe with tasks
darwin[tasks].head()

,air_time3,disp_index3,gmrt_in_air3,gmrt_on_paper3,max_x_extension3,max_y_extension3,mean_acc_in_air3,mean_acc_on_paper3,mean_gmrt3,mean_jerk_in_air3,...,mean_gmrt18,mean_jerk_in_air18,mean_jerk_on_paper18,mean_speed_in_air18,mean_speed_on_paper18,num_of_pendown18,paper_time18,pressure_mean18,pressure_var18,total_time18
0,4345,0.000013,330.487573,106.611229,4495,765,0.692386,0.178768,218.549401,0.125262,...,164.158874,0.032739,0.021847,2.122297,3.446748,3,1990,1766.065327,250250.39270,3320
1,15885,0.000013,240.382372,107.648180,4498,2386,0.890156,0.133220,174.015276,0.161044,...,72.200299,0.023843,0.017654,1.739891,0.908762,6,6310,1657.667987,267168.18060,8815
2,420,0.000009,82.562392,146.116295,4645,266,0.202899,0.102299,114.339344,0.026745,...,157.799640,0.027656,0.017302,1.470192,2.933225,4,2100,1840.950000,113069.76180,2625
3,3795,0.000014,323.273194,75.711596,4568,966,0.268581,0.132872,199.492395,0.039607,...,267.363709,0.401766,0.018004,7.782790,2.600172,6,2820,1473.060284,340721.07080,5935
4,2255,0.000012,214.958135,70.517185,4076,317,0.233940,0.157008,142.737660,0.029026,...,149.172531,0.032314,0.016255,3.123961,2.268141,4,2200,1974.238636,74065.03169,3235

In [36]:
# Create new dataframe
# Concat tasks, class_col, id_col into new dataframe
darwin2 = pd.concat([id_col, darwin[tasks], class_col], axis = 1)
darwin2.head()

,ID,air_time3,disp_index3,gmrt_in_air3,gmrt_on_paper3,max_x_extension3,max_y_extension3,mean_acc_in_air3,mean_acc_on_paper3,mean_gmrt3,...,mean_jerk_in_air18,mean_jerk_on_paper18,mean_speed_in_air18,mean_speed_on_paper18,num_of_pendown18,paper_time18,pressure_mean18,pressure_var18,total_time18,class
0,id_1,4345,0.000013,330.487573,106.611229,4495,765,0.692386,0.178768,218.549401,...,0.032739,0.021847,2.122297,3.446748,3,1990,1766.065327,250250.39270,3320,P
1,id_2,15885,0.000013,240.382372,107.648180,4498,2386,0.890156,0.133220,174.015276,...,0.023843,0.017654,1.739891,0.908762,6,6310,1657.667987,267168.18060,8815,P
2,id_3,420,0.000009,82.562392,146.116295,4645,266,0.202899,0.102299,114.339344,...,0.027656,0.017302,1.470192,2.933225,4,2100,1840.950000,113069.76180,2625,P
3,id_4,3795,0.000014,323.273194,75.711596,4568,966,0.268581,0.132872,199.492395,...,0.401766,0.018004,7.782790,2.600172,6,2820,1473.060284,340721.07080,5935,P
4,id_5,2255,0.000012,214.958135,70.517185,4076,317,0.233940,0.157008,142.737660,...,0.032314,0.016255,3.123961,2.268141,4,2200,1974.238636,74065.03169,3235,P

In [39]:
# Export new dataframe as a csv
darwin2.to_csv('darwin2.csv',index=False)